#!/bin/sh
git checkout gh-pages > /dev/null 2>&1
git rm -rf . > /dev/null 2>&1
git checkout master -- www/* > /dev/null 2>&1
git add . > /dev/null 2>&1
git commit -m "Update from master" > /dev/null 2>&1
git checkout master > /dev/null 2>&1